# Chapter 11. 데이터 분석을 위한 패키지

넘파이와 판다스 = 데이터 과학 및 분석에 많이 사용되는 패키지라 차후 분석 및 처리때 유용

**NumPy** Numeric Python - 파이썬으로 과학 연산을 쉽고 빠르게 만든 패키지. 다차원 배열 데이터를 효과적으로 처리.


array  n차원 n axis (오로지 한 타입만)

1D array | 2D array | 3D array  
---|---|--- 
(4,) | (2,3) | (4,3,2)
수평방향, axis 0 | axis 0 수직방향, 수평방향 axis 1 | axis 1 가로 axis 2 세로 axis 3 높이
| 2행 3열 | 

**Pandas**[https://assets.datacamp.com/blog_assets/PandasPythonForDataScience.pdf]
1. series : one-dimensional labeled array capable of holding any data type
2. DataFrame : two-dimensional labeled data structure with columns of potentially different types   
   (Column끼리 같은 데이터 타입. series 를 세로형으로 모은게 됨)

In [1]:
import pandas as pd 
data = {'Country': ['Belgium', 'India', 'Brazil'],
 'Capital': ['Brussels', 'New Delhi', 'Brasília'],
 'Population': [11190846, 1303171035, 207847528]}
df = pd.DataFrame(data, columns=['Country', 'Capital', 'Population'])
print(df)

   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasília   207847528


## 11.1 배열 데이터를 효과적으로 다루는 NumPy

### 11.1.1 배열 생성하기
배열(array) - 순서가 있는 같은 종류이ㅡ 데이터가 저장된 집합

In [2]:
import numpy as np

#### 시퀀스 데이터로부터 배열 생성
`arr_obj = np.array(seq_data)`

정수 array 생성

In [3]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

정수와 실수의 혼합: 정수는 .이 생김

In [4]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

배열 객체의 타입 확인
* `int32` - 32비트 정수 타입
* `int64` - 64비트 정수 타입

In [5]:
a1.dtype

dtype('int32')

In [6]:
a2.dtype

dtype('float64')

다차원 배열 생성

In [7]:
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 범위를 지정해 배열 생성 
`arr_obj = np.range([start,] stop[,step])`


In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

m\*n 행렬: `.reshape(m,n)` 이용  

In [11]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

`NumPy` 배열의 형태 를 알기 위해 `ndarray.shape` 실행

In [12]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [13]:
b2 = np.arange(5)
b2.shape

(5,)

In [14]:
b2

array([0, 1, 2, 3, 4])

범위의 시작과 끝, 데이터의 개수를 지정해 배열 생성   
예) 0부터 π까지 동일한 간격으로 나눈 20개의 데이터

In [15]:
np.linspace(0, np.pi, 20 )

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [16]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#### 특별한 형태의 배열 생성   
괄호가 두개인 이유. 안의 괄호는 tuple 만들기 위함.
> `zeroes()` 모든 원소가 0   
 `ones()` 모든 원소가 1